POST http://localhost:5000/api/movies
Content-Type: application/json

{
    "title": "Lorehirefvfh",
    "director": "Orson Wells",
    "year": "1941",
    "color": false,
    "duration": "120"
}
###
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "firstname": "Rohan",
    "lastname": "Moli",
    "email": "rohan@mail.com",
    "city": "Tokyo",
    "language": "French"
}
###
PUT http://localhost:5000/api/users/8
Content-Type: application/json

{
    "firstname": "Rohan",
    "lastname": "Moli",
    "email": "rohan@mail.com",
    "city": "France",
    "language": "French"
}
###
DELETE http://localhost:5000/api/users/8
